Repository ShinMyohan/MyoMiFrontend, pull requests merged in 2023-03, with the labels that each got.

#89 상단 메뉴바와 스크롤 메뉴바 생성
  css/basic.css
  css/index.css
  css/mypage/mypage.css
  html/index.html
  html/product/productlist.html
  js/basic.js
  js/index.js
Labels: design

#90 리뷰리스트 html 리뷰리스트 css 디자인
  css/review/reviewlist.css
  html/review/reviewlist.html
Labels: design

#91 포인트, 쿠폰 js 생성, 게시판, 댓글 일부 수정
  css/board/boardList.css
  css/board/boarddetail.css
  css/coupon/coupon.css
  css/myboardlist/myboardlist.css
  css/point/point.css
  html/board/boardList.html
  html/board/boardadd.html
  html/board/boardedit.html
  html/board/detail.html
  html/coupon/couponlist.html
  html/myboardlist/myboardlist.html
  html/point/pointlist.html
  js/board/basic.js
  js/board/boardAdd.js
  js/board/boardEdit.js
  js/board/boardList.js
  js/board/detail.js
  js/coupon/coupon.js
  js/myboardlist/myboardlist.js
  js/mypage/userinfo.js
  js/point/pointlist.js
Labels: feat

#93 장바구니, 주문, 결제, 채팅 기능 구현 & 리팩토링
  css/cart/cartinfo.css
  css/chat/room.css
  css/mypage/myorderdetail.css
  css/mypage/myorderlist.css
  css/mypage/mypage.css
  css/order/order.css
  css/order/payment.css
  css/user/login.css
  html/cart/cartinfo.html
  html/chat/room.html
  html/mypage/myorderdetail.html
  html/mypage/myorderlist.html
  html/order/order.html
  html/order/payment.html
  js/basic.js
  js/cart/cartinfo.js
  js/chat/room.js
  js/mypage/myorderdetail.js
  js/mypage/myorderlist.js
  js/order/order.js
  js/order/payment.js
Labels: feat, refactoring

#96 리뷰,공지사항,관리자 페이지 생성 및 수정
  css/admin/seller-approve-detail.css
  css/admin/seller-approve.css
  css/notice/noticeadd.css
  css/notice/noticedetail.css
  css/notice/noticelist.css
  css/review/bestreviewselect.css
  css/review/media.css
  css/review/review-mypage.css
  css/review/review_edit.css
  css/review/review_write.css
  css/review/reviewdetail.css
  css/review/reviewlist.css
  html/admin/sellerdetail.html
  html/admin/sellerinfolist.html
  html/notice/noticeadd.html
  html/notice/noticedetail.html
  html/notice/noticelist.html
  html/review/addreview.html
  html/review/bestreviewlist.html
  html/review/detailbestreview.html
  html/review/detailreview.html
  html/review/editreview.html
  html/review/reviewdetail.html
  html/review/reviewedit.html
  html/review/reviewlist.html
  html/review/reviewmypage.html
  html/review/seller-reviewlist.html
  js/admin/seller-detail.js
  js/admin/sellerinfolist.js
  js/notice/noticeadd.js
  js/notice/noticedetail.js
  js/notice/noticelist.js
  js/review/addreview.js
  js/review/basic.js
  js/review/bestreviewdetail.js
  js/review/bestreviewlist.js
  js/review/editreview.js
  js/review/reviewdetail.js
  js/review/reviewlist.js
  js/review/reviewmypage.js
  js/review/seller-reviewlist.js
Labels: feat

#99 게시판 수정시 사진 기능 업데이트, 글 목록 페이징 추가
  css/board/boardAdd.css
  css/board/boardList.css
  css/board/boarddetail.css
  css/coupon/coupon.css
  css/myboardlist/myboardlist.css
  css/point/point.css
  html/board/boardList.html
  html/board/boardadd.html
  html/board/boardedit.html
  html/board/detail.html
  html/coupon/couponlist.html
  html/myboardlist/myboardlist.html
  html/point/pointlist.html
  js/board/boardAdd.js
  js/board/boardEdit.js
  js/board/boardList.js
  js/board/detail.js
  js/coupon/coupon.js
  js/myboardlist/myboardlist.js
  js/mypage/userinfo.js
  js/point/pointlist.js
Labels: feat

#101 Feat: Qna Paging & Seller Sign-out
  css/follow/mypage-followlist.css
  css/partner/seller-addform.css
  css/partner/seller-signup.css
  css/qna/mypage-qna.css
  css/qna/seller-mypage-qnalist.css
  css/sellerpage/orderlist.css
  css/sellerpage/seller-signout.css
  html/follow/mypage-followlist.html
  html/partner/seller-addform.html
  html/partner/seller-signup.html
  html/qna/my-qnadetail.html
  html/qna/my-qnalist.html
  html/qna/qnalist.html
  html/qna/sellerpage-qnalist.html
  html/sellerpage/orderlist.html
  html/sellerpage/seller-signout.html
  html/store/follow.html
  js/follow/mypage-followlist.js
  js/partner/seller-addform.js
  js/partner/seller-signup.js
  js/qna/mypage-qna-detail.js
  js/qna/mypage-qna.js
  js/qna/qnalist.js
  js/qna/seller-mypage-qnalist.js
  js/sellerpage/orderlist.js
  js/sellerpage/productlist.js
  js/sellerpage/seller-signout.js
  js/sellerpage/sellerinfo.js
  js/store/follow.js
Labels: feat

#102 예외처리 추가 & 리팩토링
  css/basic.css
  css/cart/cartinfo.css
  css/chat/room.css
  css/index.css
  css/mypage/myorderdetail.css
  css/mypage/myorderlist.css
  css/order/order.css
  html/cart/cartinfo.html
  html/index.html
  html/mypage/myorderdetail.html
  html/mypage/myorderlist.html
  html/mypage/mypage.html
  html/order/order.html
  html/order/payment.html
  html/product/productinfo.html
  js/basic.js
  js/cart/cartadd.js
  js/cart/cartinfo.js
  js/chat/room.js
  js/index.js
  js/mypage/myorderdetail.js
  js/mypage/myorderlist.js
  js/order/order.js
  js/order/payment.js
  js/product/productinfo.js
  js/product/productlist.js
Labels: feat, refactoring

#104 일부 예외처리 추가
  css/board/boardAdd.css
  css/board/boardList.css
  css/board/boarddetail.css
  css/myboardlist/myboardlist.css
  html/board/boardList.html
  html/board/boardadd.html
  html/board/boardedit.html
  html/board/detail.html
  html/coupon/couponlist.html
  html/myboardlist/myboardlist.html
  html/point/pointlist.html
  js/board/boardAdd.js
  js/board/boardEdit.js
  js/board/boardList.js
  js/board/detail.js
  js/coupon/coupon.js
  js/myboardlist/myboardlist.js
Labels: upgrade

#107 문자 인증 기능 구현 + 예외처리 추가 및 플로트 메뉴에 페이지 연결
  css/basic.css
  css/mypage/mypage.css
  css/sellerpage/sellerproductlist.css
  css/user/signup.css
  html/index.html
  html/mypage/mypage.html
  html/product/productinfo.html
  html/product/productsearch.html
  html/product/sellerstore.html
  html/sellerpage/sellerproductlist.html
  html/user/signup.html
  js/basic.js
  js/mypage/myorderlist.js
  js/mypage/userinfo.js
  js/product/productinfo.js
  js/sellerpage/sellerproductlist.js
  js/user/signup.js
Labels: feat, refactoring

#109 판매자 & 문의 일부 기능 업데이트
  css/follow/mypage-followlist.css
  css/partner/seller-addform.css
  css/partner/seller-signup.css
  css/qna/mypage-qna-detail.css
  css/qna/mypage-qna.css
  css/qna/qnalist.css
  css/qna/seller-mypage-qnalist.css
  css/sellerpage/orderlist.css
  css/sellerpage/seller-signout.css
  html/follow/mypage-followlist.html
  html/partner/seller-addform.html
  html/partner/seller-signup.html
  html/qna/my-qnadetail.html
  html/qna/my-qnalist.html
  html/qna/qnalist.html
  html/qna/sellerpage-qnalist.html
  html/sellerpage/orderlist.html
  html/sellerpage/seller-signout.html
  js/follow/mypage-followlist.js
  js/partner/seller-addform.js
  js/qna/mypage-qna-detail.js
  js/qna/mypage-qna.js
  js/qna/qnalist.js
  js/qna/seller-mypage-qnalist.js
  js/sellerpage/orderlist.js
Labels: feat

#110 마이페이지 메뉴바 링크 수정, css, js 살짝 수정
  css/coupon/coupon.css
  html/board/boardedit.html
  html/coupon/couponlist.html
  html/myboardlist/myboardlist.html
  html/point/pointlist.html
  js/board/boardAdd.js
  js/board/boardEdit.js
  js/board/boardList.js
Labels: cleanup, upgrade

#111 리뷰, 공지사항, 관리자 페이지 기능 및 디자인 수정
  css/admin/adminpage.css
  css/admin/detailseller.css
  css/admin/sellerlist.css
  css/notice/noticeadd.css
  css/review/review_edit.css
  css/review/review_write.css
  html/admin/sellerdetail.html
  html/admin/sellerinfolist.html
  html/mypage/reviewdetail.html
  html/mypage/reviewedit.html
  html/mypage/reviewmypage.html
  html/sellerpage/sellerreviewlist.html
  js/admin/seller-detail.js
  js/admin/sellerinfolist.js
  js/notice/noticelist.js
  js/review/editreview.js
  js/review/reviewmypage.js
  js/review/seller-reviewlist.js
Labels: feat

#113 판매자&팔로우&문의 CSS 수정 및 업데이트
  css/follow/mypage-followlist.css
  css/partner/seller-addform.css
  css/partner/seller-signup.css
  css/qna/mypage-qna-detail.css
  css/qna/qnalist.css
  css/qna/seller-mypage-qnalist.css
  css/sellerpage/orderlist.css
  css/sellerpage/seller-signout.css
  html/follow/mypage-followlist.html
  html/partner/seller-addform.html
  html/partner/seller-signup.html
  html/qna/my-qnadetail.html
  html/qna/my-qnalist.html
  html/qna/qnalist.html
  js/follow/mypage-followlist.js
  js/qna/mypage-qna.js
  js/qna/qnalist.js
Labels: design

#114 셀러 승인 상태 변경시 문자알림 기능 추가 및 기능 보완
  css/mypage/mypage.css
  css/product/productlist.css
  css/store/follow.css
  html/mypage/mypage.html
  html/product/productinfo.html
  html/product/productlist.html
  html/product/productsearch.html
  html/product/sellerstore.html
  html/seller/productadd.html
  html/seller/productupdate.html
  js/admin/seller-detail.js
  js/basic.js
  js/cart/cartremove.js
  js/mypage/mypagemain.js
  js/mypage/userinfo.js
  js/product/productinfo.js
  js/product/productlist.js
  js/seller/productadd.js
  js/sellerpage/sellerproductlist.js
  js/user/signup.js
Labels: feat

#115 상품 상세보기 시 리뷰, 베스트리뷰 볼 수 있게 수정 그리고 공지사항, 리뷰 글자수 제한 수정, 리뷰 작성되게 에러 수정
  css/admin/detailseller.css
  css/review/reviewlist.css
  html/mypage/reviewedit.html
  html/notice/notice-edit.html
  html/notice/noticeadd.html
  html/product/productinfo.html
  html/review/addreview.html
  js/notice/notice-edit.js
  js/notice/noticeadd.js
  js/notice/noticedetail.js
  js/notice/noticelist.js
  js/product/productinfo.js
  js/review/addreview.js
  js/review/editreview.js
  js/review/seller-reviewlist.js
  js/sellerpage/sellerproductlist.js
Labels: feat, fix
