Repository ShinMyohan/MyoMiFrontend, pull requests merged in 2023-01, with the labels that each got.

#3 메인 페이지, 상품 목록 불러오기 페이지
  .gitignore
  css/basic.css
  css/index.css
  css/product/productinfo.css
  css/product/productlist.css
  html/index.html
  html/product/dosiraklist.html
  html/product/productadd.html
  html/product/productinfo.html
  html/product/productlist.html
  js/basic.js
  js/index.js
  js/product/productlist.js
Labels: feat, refactoring

#6 상품 리스트 / 상품 상세보기 페이지
  .gitignore
  css/basic.css
  css/index.css
  css/product/productinfo.css
  css/product/productlist.css
  html/index.html
  html/product/dosiraklist.html
  html/product/productinfo.html
  html/product/productlist.html
  js/basic.js
  js/index.js
  js/product/productinfo.js
  js/product/productlist.js
Labels: feat, refactoring

#8 주문 페이지 구현
  .gitignore
  css/order/order.css
  html/order/order.html
  imgs/jojini.png
  imgs/shin.png
  js/order/delivery.js
  js/order/order.js
Labels: feat

#12 글 수정기능 구현 및 기능 보완
  css/board/boardList.css
  css/board/boarddetail.css
  css/board/bootstrap.min.css
  css/board/font-awesome.min.css
  css/board/style.css
  html/board/boardList.html
  html/board/boardadd.html
  html/board/boardedit.html
  html/board/detail.html
  js/board/basic.js
  js/board/boardAdd.js
  js/board/boardEdit.js
  js/board/boardList.js
  js/board/detail.js
Labels: feat

#13 주문 상품 정보 불러오기
  css/order/order.css
  html/order/order.html
  js/order/order.js
Labels: feat

#14 주문 기능 보완
  html/order/order.html
  js/order/order.js
Labels: feat

#15 리뷰 작성, 리뷰목록보기, 베스트리뷰 목록보기 프런트 기능 구현
  css/review/media.css
  css/review/review_write.css
  css/review/reviewlist.css
  css/review/star.css
  html/review/addreview.html
  html/review/bestreviewlist.html
  html/review/reviewlist.html
  js/review/addreview.js
  js/review/basic.js
  js/review/bestreviewlist.js
  js/review/reviewlist.js
Labels: cleanup, feat

#38 장바구니 ajax 및 디자인 수정
  css/cart/cartinfo.css
  html/cart/cartinfo.html
  js/basic.js
  js/cart/cartinfo.js
  js/cart/cartremove.js
Labels: feat, design
